server {
    listen 80;
    server_name localhost;

    include /etc/nginx/mime.types;
    root /usr/share/nginx/html;

    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    types {
        application/wasm wasm;
    }

    location = /NotoSerifCJK-VF.otf.ttc {
        expires 1M;
        add_header Cache-Control "public";
    }
}