[[config]]
type = "GoogleRssSearch"
query = "(war OR disruption OR earthquake OR breaking) when:1d"
update_interval = 1200

[[config]]
type = "GoogleRssSearch"
query = "(apple OR android OR iOS OR macOS OR iPadOS OR Google) when:7d"
update_interval = 2400

[[config]]
type = "HackerNews"
query = ""
update_interval = 1200

[[config]]
type = "GoogleRssSearch"
query = "(Gemini OR OpenAI OR GPT OR Claude OR Deepseek OR AI) when: 7d"
update_interval = 2400

[[config]]
type = "GoogleRssSearch"
query = "(CVE OR vulnerability) when: 7d"
update_interval = 2400

[[config]]
type = "GoogleRssSearch"
query = "from:404media.co"
update_interval = 2400

[[config]]
type = "Youtube"
query = "UCx-PpwbajI5ToAY0WwJO2Kg" # https://www.youtube.com/@PortalRunner
update_interval = 1200

[[config]]
type = "Youtube"
query = "UCHnyfMqiRRG1u-2MsSQLbXA" # https://www.youtube.com/veritasium
update_interval = 1200

[[config]]
type = "Youtube"
query = "UC-eegKVWEgBCa4OzjnK_PtA" # http://youtube.com/@TLDRnewsEU
update_interval = 1200

[[config]]
type = "Youtube"
query = "UC-ufRLYrXxrIEApGn9VG5pQ" # https://www.youtube.com/@rejectconvenience
update_interval = 1200

[[config]]
type = "Youtube"
query = "UCuQT7Vc3OjjZuGkqehNxb6w" # https://www.youtube.com/@enricotartarotti
update_interval = 1200

[[config]]
type = "Youtube"
query = "UCqykZoZjaOPb6i_Y5gk0kLQ" # https://www.youtube.com/@christophe
update_interval = 1200

[[config]]
type = "Youtube"
query = "UCxkM67T_Iele-mRVUiBkRqg" # https://www.youtube.com/@jetlagthegame
update_interval = 1200

[[config]]
type = "Youtube"
query = "UC-uhvujip5deVcEtLxnW8qg" #  https://www.youtube.com/@TLDRnewsGLOBAL
update_interval = 1200

[[config]]
type = "Youtube"
query = "UCGudGqToOw9hWGR88W9Jutg" #  https://www.youtube.com/@Howtown
update_interval = 1200

[[config]]
type = "Youtube"
query = "UCii9ezsUa_mBiSdw0PtSOaw" # https://www.youtube.com/@hoog-youtube
update_interval = 1200

[[config]]
type = "Youtube"
query = "UCODHrzPMGbNv67e84WDZhQQ" # https://www.youtube.com/@fern-tv
update_interval = 1200

[[config]]
type = "Reddit"
query = "ProgrammerHumor"
update_interval = 450

[[config]]
type = "Rss2Generic"
query = "https://feeds.bbci.co.uk/news/rss.xml"
update_interval = 900

[[config]]
type = "Rss2Generic"
query = "https://feeds.bbci.co.uk/news/world/rss.xml"
update_interval = 900

[[config]]
type = "Rss2Generic"
query = "https://www.euronews.com/rss?format=mrss&level=theme&name=news"
update_interval = 900
